/**
 * 이미지 코드(예: "image_0_0_0.png")를 인자로 받아서
 * 해당하는 이미지의 require 구문을 반환하는 함수입니다.
 * 이 방식을 사용하면 이미지가 실제로 화면에 필요할 때만 메모리에 로드되어
 * 앱의 메모리 부족 문제를 해결할 수 있습니다.
 */
export function getCharacterImage(code) {
  switch (code) {
    case "default_character.png":
      return require("../assets/character/default_character.png");
    case "image_0_0_0.png":
      return require("../assets/character/0,0,0.png");
    case "image_0_0_1.png":
      return require("../assets/character/0,0,1.png");
    case "image_0_0_2.png":
      return require("../assets/character/0,0,2.png");
    case "image_0_0_3.png":
      return require("../assets/character/0,0,3.png");
    case "image_0_0_4.png":
      return require("../assets/character/0,0,4.png");
    case "image_0_0_5.png":
      return require("../assets/character/0,0,5.png");
    case "image_0_1_0.png":
      return require("../assets/character/0,1,0.png");
    case "image_0_1_1.png":
      return require("../assets/character/0,1,1.png");
    case "image_0_1_2.png":
      return require("../assets/character/0,1,2.png");
    case "image_0_1_3.png":
      return require("../assets/character/0,1,3.png");
    case "image_0_1_4.png":
      return require("../assets/character/0,1,4.png");
    case "image_0_1_5.png":
      return require("../assets/character/0,1,5.png");
    case "image_0_2_0.png":
      return require("../assets/character/0,2,0.png");
    case "image_0_2_1.png":
      return require("../assets/character/0,2,1.png");
    case "image_0_2_2.png":
      return require("../assets/character/0,2,2.png");
    case "image_0_2_3.png":
      return require("../assets/character/0,2,3.png");
    case "image_0_2_4.png":
      return require("../assets/character/0,2,4.png");
    case "image_0_2_5.png":
      return require("../assets/character/0,2,5.png");
    case "image_0_3_0.png":
      return require("../assets/character/0,3,0.png");
    case "image_0_3_1.png":
      return require("../assets/character/0,3,1.png");
    case "image_0_3_2.png":
      return require("../assets/character/0,3,2.png");
    case "image_0_3_3.png":
      return require("../assets/character/0,3,3.png");
    case "image_0_3_4.png":
      return require("../assets/character/0,3,4.png");
    case "image_0_3_5.png":
      return require("../assets/character/0,3,5.png");
    case "image_0_4_0.png":
      return require("../assets/character/0,4,0.png");
    case "image_0_4_1.png":
      return require("../assets/character/0,4,1.png");
    case "image_0_4_2.png":
      return require("../assets/character/0,4,2.png");
    case "image_0_4_3.png":
      return require("../assets/character/0,4,3.png");
    case "image_0_4_4.png":
      return require("../assets/character/0,4,4.png");
    case "image_0_4_5.png":
      return require("../assets/character/0,4,5.png");
    case "image_0_5_0.png":
      return require("../assets/character/0,5,0.png");
    case "image_0_5_1.png":
      return require("../assets/character/0,5,1.png");
    case "image_0_5_2.png":
      return require("../assets/character/0,5,2.png");
    case "image_0_5_3.png":
      return require("../assets/character/0,5,3.png");
    case "image_0_5_4.png":
      return require("../assets/character/0,5,4.png");
    case "image_0_5_5.png":
      return require("../assets/character/0,5,5.png");
    case "image_1_0_0.png":
      return require("../assets/character/1,0,0.png");
    case "image_1_0_1.png":
      return require("../assets/character/1,0,1.png");
    case "image_1_0_2.png":
      return require("../assets/character/1,0,2.png");
    case "image_1_0_3.png":
      return require("../assets/character/1,0,3.png");
    case "image_1_0_4.png":
      return require("../assets/character/1,0,4.png");
    case "image_1_0_5.png":
      return require("../assets/character/1,0,5.png");
    case "image_1_1_0.png":
      return require("../assets/character/1,1,0.png");
    case "image_1_1_1.png":
      return require("../assets/character/1,1,1.png");
    case "image_1_1_2.png":
      return require("../assets/character/1,1,2.png");
    case "image_1_1_3.png":
      return require("../assets/character/1,1,3.png");
    case "image_1_1_4.png":
      return require("../assets/character/1,1,4.png");
    case "image_1_1_5.png":
      return require("../assets/character/1,1,5.png");
    case "image_1_2_0.png":
      return require("../assets/character/1,2,0.png");
    case "image_1_2_1.png":
      return require("../assets/character/1,2,1.png");
    case "image_1_2_2.png":
      return require("../assets/character/1,2,2.png");
    case "image_1_2_3.png":
      return require("../assets/character/1,2,3.png");
    case "image_1_2_4.png":
      return require("../assets/character/1,2,4.png");
    case "image_1_2_5.png":
      return require("../assets/character/1,2,5.png");
    case "image_1_3_0.png":
      return require("../assets/character/1,3,0.png");
    case "image_1_3_1.png":
      return require("../assets/character/1,3,1.png");
    case "image_1_3_2.png":
      return require("../assets/character/1,3,2.png");
    case "image_1_3_3.png":
      return require("../assets/character/1,3,3.png");
    case "image_1_3_4.png":
      return require("../assets/character/1,3,4.png");
    case "image_1_3_5.png":
      return require("../assets/character/1,3,5.png");
    case "image_1_4_0.png":
      return require("../assets/character/1,4,0.png");
    case "image_1_4_1.png":
      return require("../assets/character/1,4,1.png");
    case "image_1_4_2.png":
      return require("../assets/character/1,4,2.png");
    case "image_1_4_3.png":
      return require("../assets/character/1,4,3.png");
    case "image_1_4_4.png":
      return require("../assets/character/1,4,4.png");
    case "image_1_4_5.png":
      return require("../assets/character/1,4,5.png");
    case "image_1_5_0.png":
      return require("../assets/character/1,5,0.png");
    case "image_1_5_1.png":
      return require("../assets/character/1,5,1.png");
    case "image_1_5_2.png":
      return require("../assets/character/1,5,2.png");
    case "image_1_5_3.png":
      return require("../assets/character/1,5,3.png");
    case "image_1_5_4.png":
      return require("../assets/character/1,5,4.png");
    case "image_1_5_5.png":
      return require("../assets/character/1,5,5.png");
    case "image_2_0_0.png":
      return require("../assets/character/2,0,0.png");
    case "image_2_0_1.png":
      return require("../assets/character/2,0,1.png");
    case "image_2_0_2.png":
      return require("../assets/character/2,0,2.png");
    case "image_2_0_3.png":
      return require("../assets/character/2,0,3.png");
    case "image_2_0_4.png":
      return require("../assets/character/2,0,4.png");
    case "image_2_0_5.png":
      return require("../assets/character/2,0,5.png");
    case "image_2_1_0.png":
      return require("../assets/character/2,1,0.png");
    case "image_2_1_1.png":
      return require("../assets/character/2,1,1.png");
    case "image_2_1_2.png":
      return require("../assets/character/2,1,2.png");
    case "image_2_1_3.png":
      return require("../assets/character/2,1,3.png");
    case "image_2_1_4.png":
      return require("../assets/character/2,1,4.png");
    case "image_2_1_5.png":
      return require("../assets/character/2,1,5.png");
    case "image_2_2_0.png":
      return require("../assets/character/2,2,0.png");
    case "image_2_2_1.png":
      return require("../assets/character/2,2,1.png");
    case "image_2_2_2.png":
      return require("../assets/character/2,2,2.png");
    case "image_2_2_3.png":
      return require("../assets/character/2,2,3.png");
    case "image_2_2_4.png":
      return require("../assets/character/2,2,4.png");
    case "image_2_2_5.png":
      return require("../assets/character/2,2,5.png");
    case "image_2_3_0.png":
      return require("../assets/character/2,3,0.png");
    case "image_2_3_1.png":
      return require("../assets/character/2,3,1.png");
    case "image_2_3_2.png":
      return require("../assets/character/2,3,2.png");
    case "image_2_3_3.png":
      return require("../assets/character/2,3,3.png");
    case "image_2_3_4.png":
      return require("../assets/character/2,3,4.png");
    case "image_2_3_5.png":
      return require("../assets/character/2,3,5.png");
    case "image_2_4_0.png":
      return require("../assets/character/2,4,0.png");
    case "image_2_4_1.png":
      return require("../assets/character/2,4,1.png");
    case "image_2_4_2.png":
      return require("../assets/character/2,4,2.png");
    case "image_2_4_3.png":
      return require("../assets/character/2,4,3.png");
    case "image_2_4_4.png":
      return require("../assets/character/2,4,4.png");
    case "image_2_4_5.png":
      return require("../assets/character/2,4,5.png");
    case "image_2_5_0.png":
      return require("../assets/character/2,5,0.png");
    case "image_2_5_1.png":
      return require("../assets/character/2,5,1.png");
    case "image_2_5_2.png":
      return require("../assets/character/2,5,2.png");
    case "image_2_5_3.png":
      return require("../assets/character/2,5,3.png");
    case "image_2_5_4.png":
      return require("../assets/character/2,5,4.png");
    case "image_2_5_5.png":
      return require("../assets/character/2,5,5.png");
    case "image_3_0_0.png":
      return require("../assets/character/3,0,0.png");
    case "image_3_0_1.png":
      return require("../assets/character/3,0,1.png");
    case "image_3_0_2.png":
      return require("../assets/character/3,0,2.png");
    case "image_3_0_3.png":
      return require("../assets/character/3,0,3.png");
    case "image_3_0_4.png":
      return require("../assets/character/3,0,4.png");
    case "image_3_0_5.png":
      return require("../assets/character/3,0,5.png");
    case "image_3_1_0.png":
      return require("../assets/character/3,1,0.png");
    case "image_3_1_1.png":
      return require("../assets/character/3,1,1.png");
    case "image_3_1_2.png":
      return require("../assets/character/3,1,2.png");
    case "image_3_1_3.png":
      return require("../assets/character/3,1,3.png");
    case "image_3_1_4.png":
      return require("../assets/character/3,1,4.png");
    case "image_3_1_5.png":
      return require("../assets/character/3,1,5.png");
    case "image_3_2_0.png":
      return require("../assets/character/3,2,0.png");
    case "image_3_2_1.png":
      return require("../assets/character/3,2,1.png");
    case "image_3_2_2.png":
      return require("../assets/character/3,2,2.png");
    case "image_3_2_3.png":
      return require("../assets/character/3,2,3.png");
    case "image_3_2_4.png":
      return require("../assets/character/3,2,4.png");
    case "image_3_2_5.png":
      return require("../assets/character/3,2,5.png");
    case "image_3_3_0.png":
      return require("../assets/character/3,3,0.png");
    case "image_3_3_1.png":
      return require("../assets/character/3,3,1.png");
    case "image_3_3_2.png":
      return require("../assets/character/3,3,2.png");
    case "image_3_3_3.png":
      return require("../assets/character/3,3,3.png");
    case "image_3_3_4.png":
      return require("../assets/character/3,3,4.png");
    case "image_3_3_5.png":
      return require("../assets/character/3,3,5.png");
    case "image_3_4_0.png":
      return require("../assets/character/3,4,0.png");
    case "image_3_4_1.png":
      return require("../assets/character/3,4,1.png");
    case "image_3_4_2.png":
      return require("../assets/character/3,4,2.png");
    case "image_3_4_3.png":
      return require("../assets/character/3,4,3.png");
    case "image_3_4_4.png":
      return require("../assets/character/3,4,4.png");
    case "image_3_4_5.png":
      return require("../assets/character/3,4,5.png");
    case "image_3_5_0.png":
      return require("../assets/character/3,5,0.png");
    case "image_3_5_1.png":
      return require("../assets/character/3,5,1.png");
    case "image_3_5_2.png":
      return require("../assets/character/3,5,2.png");
    case "image_3_5_3.png":
      return require("../assets/character/3,5,3.png");
    case "image_3_5_4.png":
      return require("../assets/character/3,5,4.png");
    case "image_3_5_5.png":
      return require("../assets/character/3,5,5.png");
    case "image_4_0_0.png":
      return require("../assets/character/4,0,0.png");
    case "image_4_0_1.png":
      return require("../assets/character/4,0,1.png");
    case "image_4_0_2.png":
      return require("../assets/character/4,0,2.png");
    case "image_4_0_3.png":
      return require("../assets/character/4,0,3.png");
    case "image_4_0_4.png":
      return require("../assets/character/4,0,4.png");
    case "image_4_0_5.png":
      return require("../assets/character/4,0,5.png");
    case "image_4_1_0.png":
      return require("../assets/character/4,1,0.png");
    case "image_4_1_1.png":
      return require("../assets/character/4,1,1.png");
    case "image_4_1_2.png":
      return require("../assets/character/4,1,2.png");
    case "image_4_1_3.png":
      return require("../assets/character/4,1,3.png");
    case "image_4_1_4.png":
      return require("../assets/character/4,1,4.png");
    case "image_4_1_5.png":
      return require("../assets/character/4,1,5.png");
    case "image_4_2_0.png":
      return require("../assets/character/4,2,0.png");
    case "image_4_2_1.png":
      return require("../assets/character/4,2,1.png");
    case "image_4_2_2.png":
      return require("../assets/character/4,2,2.png");
    case "image_4_2_3.png":
      return require("../assets/character/4,2,3.png");
    case "image_4_2_4.png":
      return require("../assets/character/4,2,4.png");
    case "image_4_2_5.png":
      return require("../assets/character/4,2,5.png");
    case "image_4_3_0.png":
      return require("../assets/character/4,3,0.png");
    case "image_4_3_1.png":
      return require("../assets/character/4,3,1.png");
    case "image_4_3_2.png":
      return require("../assets/character/4,3,2.png");
    case "image_4_3_3.png":
      return require("../assets/character/4,3,3.png");
    case "image_4_3_4.png":
      return require("../assets/character/4,3,4.png");
    case "image_4_3_5.png":
      return require("../assets/character/4,3,5.png");
    case "image_4_4_0.png":
      return require("../assets/character/4,4,0.png");
    case "image_4_4_1.png":
      return require("../assets/character/4,4,1.png");
    case "image_4_4_2.png":
      return require("../assets/character/4,4,2.png");
    case "image_4_4_3.png":
      return require("../assets/character/4,4,3.png");
    case "image_4_4_4.png":
      return require("../assets/character/4,4,4.png");
    case "image_4_4_5.png":
      return require("../assets/character/4,4,5.png");
    case "image_4_5_0.png":
      return require("../assets/character/4,5,0.png");
    case "image_4_5_1.png":
      return require("../assets/character/4,5,1.png");
    case "image_4_5_2.png":
      return require("../assets/character/4,5,2.png");
    case "image_4_5_3.png":
      return require("../assets/character/4,5,3.png");
    case "image_4_5_4.png":
      return require("../assets/character/4,5,4.png");
    case "image_4_5_5.png":
      return require("../assets/character/4,5,5.png");
    case "image_5_0_0.png":
      return require("../assets/character/5,0,0.png");
    case "image_5_0_1.png":
      return require("../assets/character/5,0,1.png");
    case "image_5_0_2.png":
      return require("../assets/character/5,0,2.png");
    case "image_5_0_3.png":
      return require("../assets/character/5,0,3.png");
    case "image_5_0_4.png":
      return require("../assets/character/5,0,4.png");
    case "image_5_0_5.png":
      return require("../assets/character/5,0,5.png");
    case "image_5_1_0.png":
      return require("../assets/character/5,1,0.png");
    case "image_5_1_1.png":
      return require("../assets/character/5,1,1.png");
    case "image_5_1_2.png":
      return require("../assets/character/5,1,2.png");
    case "image_5_1_3.png":
      return require("../assets/character/5,1,3.png");
    case "image_5_1_4.png":
      return require("../assets/character/5,1,4.png");
    case "image_5_1_5.png":
      return require("../assets/character/5,1,5.png");
    case "image_5_2_0.png":
      return require("../assets/character/5,2,0.png");
    case "image_5_2_1.png":
      return require("../assets/character/5,2,1.png");
    case "image_5_2_2.png":
      return require("../assets/character/5,2,2.png");
    case "image_5_2_3.png":
      return require("../assets/character/5,2,3.png");
    case "image_5_2_4.png":
      return require("../assets/character/5,2,4.png");
    case "image_5_2_5.png":
      return require("../assets/character/5,2,5.png");
    case "image_5_3_0.png":
      return require("../assets/character/5,3,0.png");
    case "image_5_3_1.png":
      return require("../assets/character/5,3,1.png");
    case "image_5_3_2.png":
      return require("../assets/character/5,3,2.png");
    case "image_5_3_3.png":
      return require("../assets/character/5,3,3.png");
    case "image_5_3_4.png":
      return require("../assets/character/5,3,4.png");
    case "image_5_3_5.png":
      return require("../assets/character/5,3,5.png");
    case "image_5_4_0.png":
      return require("../assets/character/5,4,0.png");
    case "image_5_4_1.png":
      return require("../assets/character/5,4,1.png");
    case "image_5_4_2.png":
      return require("../assets/character/5,4,2.png");
    case "image_5_4_3.png":
      return require("../assets/character/5,4,3.png");
    case "image_5_4_4.png":
      return require("../assets/character/5,4,4.png");
    case "image_5_4_5.png":
      return require("../assets/character/5,4,5.png");
    case "image_5_5_0.png":
      return require("../assets/character/5,5,0.png");
    case "image_5_5_1.png":
      return require("../assets/character/5,5,1.png");
    case "image_5_5_2.png":
      return require("../assets/character/5,5,2.png");
    case "image_5_5_3.png":
      return require("../assets/character/5,5,3.png");
    case "image_5_5_4.png":
      return require("../assets/character/5,5,4.png");
    case "image_5_5_5.png":
      return require("../assets/character/5,5,5.png");
    default:
      // case에 없는 코드가 들어오거나 null, undefined일 경우를 대비한 기본값
      return require("../assets/character/default_character.png");
  }
}