export const storeItemImageMap = {
  "Wooden_Chair": require("../assets/storeItems/Wooden_Chair.png"),
  "Iron_Chair": require("../assets/storeItems/Iron_Chair.png"),
  "Designer_Chair": require("../assets/storeItems/Designer_Chair.png"),
  "Wooden_Sofa": require("../assets/storeItems/Wooden_Sofa.png"),
  "Cushioned_Sofa": require("../assets/storeItems/Cushioned_Sofa.png"),
  "Iron_Sofa": require("../assets/storeItems/Iron_Sofa.png"),
  "Designer_Sofa": require("../assets/storeItems/Designer_Sofa.png"),
  "Leather_Sofa": require("../assets/storeItems/Leather_Sofa.png"),
  "Modular_Sofa": require("../assets/storeItems/Modular_Sofa.png"),
  "Vintage_Fabric_Sofa": require("../assets/storeItems/Vintage_Fabric_Sofa.png"),
  "Iron_Window": require("../assets/storeItems/Iron_Window.png"),
  "Wooden_Clock": require("../assets/storeItems/Wooden_Clock.png"),
  "Cheap_Frame": require("../assets/storeItems/Cheap_Frame.png"),
  "Expensive_Frame": require("../assets/storeItems/Expensive_Frame.png"),
  "Modern_Wall_Shelf": require("../assets/storeItems/Modern_Wall_Shelf.png"),
  "Vintage_Mirror": require("../assets/storeItems/Vintage_Mirror.png"),
  "LED_Neon_Sign": require("../assets/storeItems/LED_Neon_Sign.png"),
  "Painting_Frame": require("../assets/storeItems/Painting_Frame.png"),
  "Hanging_Plant": require("../assets/storeItems/Hanging_Plant.png"),
  "World_Map_Decoration": require("../assets/storeItems/World_Map_Decoration.png"),
  "Standing_Light": require("../assets/storeItems/Standing_Light.png"),
  "Christmas_Tree": require("../assets/storeItems/Christmas_Tree.png"),
  "Modern_Rug": require("../assets/storeItems/Modern_Rug.png"),
  "Large_Flowerpot": require("../assets/storeItems/Large_Flowerpot.png"),
  "Vintage_Dresser": require("../assets/storeItems/Vintage_Dresser.png"),
  "Robot_Vacuum_Cleaner": require("../assets/storeItems/Robot_Vacuum_Cleaner.png"),
  "Book_Stack": require("../assets/storeItems/Book_Stack.png"),
  "Mini_Fireplace": require("../assets/storeItems/Mini_Fireplace.png"),
  "Full-length_Mirror": require("../assets/storeItems/Full-length_Mirror.png"),
  "Antique_Jewelry_Box ": require("../assets/storeItems/Antique_Jewelry_Box.png"),
  default: require("../assets/storeItems/empty_space.png"),
    /* "원룸": require("./assets/storeItems/원룸.png"),
  "빌라": require("./assets/storeItems/빌라.png"),
  "아파트": require("./assets/storeItems/아파트.png"),
  "스위트룸": require("./assets/storeItems/스위트룸.png"),
  "고풍스러운_서재": require("./assets/storeItems/고풍스러운_서재.png"),
  "미니멀리스트_거실": require("./assets/storeItems/미니멀리스트_거실.png"),
  "화려한_펜트하우스": require("./assets/storeItems/화려한_펜트하우스.png"),
  "일본식_다다미방": require("./assets/storeItems/일본식_다다미방.png"),
  "유럽풍_클래식_인테리어": require("./assets/storeItems/유럽풍_클래식_인테리어.png"),
  "따뜻한_카페_스타일_공간": require("./assets/storeItems/따뜻한_카페_스타일_공간.png"),*/
};